#pragma once
#ifndef BLOCKS_GAME_COMMON_H
#define BLOCKS_GAME_COMMON_H

#define DEBUG_GAME_FLOW

#ifdef DEBUG_GAME_FLOW

#define LOGO_SCREEN_DURATION_IN_FRAMES 60
#define NUM_PLAYER_LIVES 2
#define BRICKS_LINES 2
#define BRICKS_PER_LINE 8
#define MASTER_VOLUME 0.0f
#define BRICKS_POSITION_Y 50
#define BRICK_RESISTANCE 1
#define SOUND_FX_VOLUME 0.2f
#define MUSIC_STREAM_VOLUME 0.8f

#else

#define LOGO_SCREEN_DURATION_IN_FRAMES 180
#define NUM_PLAYER_LIVES 5
#define BRICKS_LINES 5
#define BRICKS_PER_LINE 20
#define MASTER_VOLUME 0.2f

#endif

enum GameScreenType {
    LOGO, TITLE, GAMEPLAY, ENDING
};
#endif //BLOCKS_GAME_COMMON_H
